# Generated by Django 2.1 on 2018-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('comments', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('argument', models.CharField(max_length=350)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='discussion',
            field=models.ManyToManyField(to='Discussion.Discussion'),
        ),
    ]
