# Generated by Django 2.1 on 2018-10-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='p_description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='p_name',
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default='', max_length=355),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=31, unique=True),
        ),
    ]
