# Generated by Django 2.1 on 2018-10-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20181001_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
